### PR TITLE
fix: Fixes type-widening bug when handling plugins.

### LINKED ISSUE #51: No type information added to Octokit instance when using an array of plugins.
**Bug**

No type information is added to an Octokit instance when using an array of plugins where one of the plugins return value is set to `void` or an empty object `{}`.

**Example**

```TypeScript
import { Octokit } from '@octokit/core'

declare function requestLog(octokit: Octokit): void;
declare function paginateRest(octokit: Octokit): { paginate: ...};
declare function queueWorker(octokit: Octokit): { add: ...};

// TypeScript is able to add methods provided by `paginateRest` and `queueWorker` plugins to the API instance for type-hinting/checking.
const API = new (Octokit.plugin(requestLog).plugin([paginateRest, queueWorker]))()

// API below is missing methods provided by `paginateRest` and `queueWorker` plugins.
const API = new (Octokit.plugin([requestLog, paginateRest, queueWorker]))()
```

**Explanation**
Because `() => void` is a supertype of any plugin that returns an object, TypeScript will widen/simplify the type of `plugins` to `() => void`, resulting in a loss of type information.

Minimal repro on [TS Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIDUctgAKASgC54A3Y4AKFElgRXWzyQDEccLqAbyR9qARngBfJuGhwkaTLnyIAQrAHxhAI1jUATFIYMA9CfgAJHDRAx4127VhYo2iCADO8bSAg4A7vAYOLRYIIFYqIi2IMBOEMieAHQMYHgeGPCoODAAtlAQAJJRMegIALzwANqIvDgANEjqMAC6qemZ-iQgqLHF0XBl8JU1dY2IRCRtQA).

**Workarounds**
To prevent a loss of type information when adding plugins to your Octokit instance: do not mix plugins that return an object filled with properties with non-object-property-filled plugins (e.g. `void` or empty objects `{}`) in the same `.plugin()` call.

Turn this: `Octokit.plugin([() => void, () => {}, paginateRest, queueWorker])`

into: `Octokit.plugin([() => void, () => {}]).plugin([paginateRest, queueWorker])`

**Solutions**

1. ~~We could add an overload to the `plugin` function to separate plugins returning void from plugins returning filled objects.~~ This won't solve the issue because plugins returning an empty object will continue to widen the array of plugin type information to `() => {}` and I don't think TypeScript is able to separate an empty object from a filled object.

2. ~~Similar to above, add an overload for `void` plugins. For `.plugin([])` calls that mix filled objects with empty objects, log an error to the console that returning empty objects messes up the type information and that the empty object must be placed in its own `.plugin()` call.~~ No way in TypeScript to differentiate between a filled object and an empty object.

### PR DESCRIPTION
**Pull request by MaximDevoir**
From the ideas that have been thrown out there to solve the issue described in #51, this is my favorite.

Instead of `.plugin(arrayOfPlugins[])`, which could lead to a type-widening error, this PR moves to use `.plugin(plugin1, plugin2, plugin3, etc...)`, where each plugin is hardcoded into the type-system

Why this approach?

I think this will be easiest on plugin authors, who don't have to change anything with how they currently develop plugins - such as having to worry about whether they need to return an object, if they return void, etc.

This will also be an easy fix for users of Octokit. `.plugin([paginateRest, queueWorker, logService])` becomes `.plugin(paginateRest, queueWorker, logService)`

**TODOs**

- [x] Continue to accept arrays as an argument (aka backward-compatible with the previous syntax)
- [x] Warn users that the syntax has changed. Provide an example of the changed syntax.

Example warning when using old syntax:

corejs-non-array-warning

Fixes #51

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -44,20 +44,31 @@ export class Octokit {
...
     const currentPlugins = this.plugins;
-    const newPlugins = Array.isArray(pluginOrPlugins)
-      ? pluginOrPlugins
-      : [pluginOrPlugins];
+    // TODO: Warn array method is deprecated and will be removed soon.
+    // const newPlugins = Array.isArray(pluginOrPlugins)
+    //   ? pluginOrPlugins
+    //   : [pluginOrPlugins];
+
+    let newPlugins: (OctokitPlugin | undefined)[] = [p1, p2, p3, p4]
```
Comment (gr2m) [inline src/index.ts]: Are only up to 4 plugins supported?

Comment (MaximDevoir) [reply src/index.ts]: No, I was thinking of doing 9 plugins, and for the last parameter it would use the spread operator so that an unlimited amount of plugins can be added, though maybe give a warning that type-information may be lost due a TS bug and that they should consider splitting into multiple `.plugin()` calls - not ideal. We can always add more parameters manually.

As I type this out, I realize more and more that this workaround is also not pretty.

I chose this solution for now because it requires no change from plug-in authors, and minimal change from users of Octokit.plugin (.plugin(arrayOfPlugins) to .plugin(plugin1, plugin2)).

Maybe the next breaking version can build another workaround that won’t require so much manual-typing in Octokit/core?

Comment (gr2m) [reply src/index.ts]: I think 9 plugins is plenty. I really do hope that some day the problem will be resolved in TypeScript itself at which point we can get rid of it.

I'd keep a workaround accepting an array of plugins until then, maybe not even log a deprecation message, just update the documentation. If people don't see typings from their Constructor they will open issues, we will see how much of a problem that will be.

Do you see another downside besides the limitation of hard-coding typings for up to 9 plugins? Because I'm okay with that, it's the best option I see at this point

File: src/index.ts [hunk 2]
```diff
@@ -42,22 +43,32 @@ export class Octokit {
...
+   * @example
+   * const API = Octokit.plugin(plugin1, plugin2, plugin3, ...)
+   */
   static plugin<
     S extends Constructor<any> & { plugins: any[] },
-    T extends OctokitPlugin | OctokitPlugin[]
-  >(this: S, pluginOrPlugins: T) {
+    T1 extends OctokitPlugin | OctokitPlugin[],
+    T2 extends OctokitPlugin[]
+  >(this: S, p1: T1, ...p2: T2) {
```
Comment (MaximDevoir) [inline src/index.ts]: Well, apparently you can use a rest parameter without risking the loss of type-information, so no need to hardcode the parameters in - hooray. It's weird, using a rest parameter deals with the `arguments` array under-the-hood... and we don't lose type-information :man_shrugging:.

File: src/index.ts (hunk 1 above)
Comment (MaximDevoir) [reply src/index.ts]: I was able to get rid of hard-coding the parameters.

The new approach uses a rest parameter for all other plugins. See conversation at https://github.com/octokit/core.js/pull/53#discussion_r395421874

File: src/index.ts (hunk 2 above)
Comment (gr2m) [reply src/index.ts]: Awesome 👏

**Comment by gr2m** [comment]
I think the `.plugin()` method now no longer accepts an array? Can we still handle that case and add a deprecation message?

**Comment by MaximDevoir** [comment]
Yeah, so it currently silently supports an array - no error or deprecation message will be shown. This PR doesn't have any breaking changes.

I can add a deprecation notice and how to migrate to the new syntax in this PR if you would like.

**Comment by gr2m** [comment]
Ah got it. Can you leave one test that keeps testing passing an array?

File: README.md [hunk 3]
```diff
@@ -342,7 +342,7 @@ See [before-after-hook](https://github.com/gr2m/before-after-hook#readme) for
 
 ## Plugins
 
-Octokit’s functionality can be extended using plugins. THe `Octokit.plugin()` method accepts a function or an array of functions and returns a new constructor.
+Octokit’s functionality can be extended using plugins. The `Octokit.plugin()` method accepts a plugin (or many) and returns a new constructor.
```
Comment (gr2m) [inline README.md]: Maybe we should add a note specifically to TypeScript users. Something like this:

`Octokit.plugin()` also accepts a single array parameter but we recommend against it, as it breaks the TypeScript/Intellisense support

Comment (MaximDevoir) [reply README.md]: The `or many` part is meant to mean plugins applied in the `.plugin(p1, p2, ...)` format - not an array. I've updated the syntax throughout the document to use the new, non-array, syntax [here](https://github.com/octokit/core.js/pull/53/files/19a56805e6bf412d89b6014d11ecb046712a4b4e#diff-04c6e90faac2675aa89e2176d2eec7d8R356-R359) and [here](https://github.com/octokit/core.js/pull/53/files/19a56805e6bf412d89b6014d11ecb046712a4b4e#diff-04c6e90faac2675aa89e2176d2eec7d8R391-R395).

Additionally, there is now a warning logged to the console when the method is supplied with an array.

This should be enough so as to not address TypeScript users specifically - as all users (js and ts) will now be nudged into the correct syntax.

File: test/plugin.test.ts [hunk 4]
```diff
@@ -1,38 +1,41 @@
...
-      () => {
-        return {
-          foo: "bar"
-        };
-      },
-      () => {
-        return { baz: "daz" };
-      }
-    ]);
+  it("supports array of plugins and warns of deprecated usage", () => {
```
Comment (MaximDevoir) [inline test/plugin.test.ts]: In reference to https://github.com/octokit/core.js/pull/53#issuecomment-602085423,

We have kept the test using an array of plugins. In this test, we're also checking for the deprecation notice too.

Comment (gr2m) [reply test/plugin.test.ts]: Sorry I forgot about it. Thanks for pointing it out
